apiVersion: v1
kind: Service
metadata:
  name: {{ include "wisecow.fullname" . }}
spec:
  selector:
    app: {{ include "wisecow.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
  type: NodePort

