name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker buildx build -t pav30/wisecow-app:${{ github.run_id }} --push .

    - name: Update tag in Helm
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' wisecow-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "pavansingh3000@gmail.com"
        git config --global user.name "pavan-3000"
        git add wisecow-chart/values.yaml
        git commit -m "Updated Helm chart tag to ${{ github.run_id }}"
        git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/pavan-3000/Containerisation-and-Deployment-of-Wisecow-Application-on-Kubernetes-.git HEAD:main
